name: pose-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - matplotlib<3.11  # can remove pin when https://github.com/y-sunflower/morethemes/issues/38 is fixed
  - numpy
  - pandas
  - ipykernel
  - plotly
  - pip
  - requests
  - geopandas
  - geopy
  - python-dotenv
  - jupyter-book<2
  - pip:
    - morethemes
    - cartopy
    - pyfonts
    - adjustText
    - google-analytics-data