name: pose-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - matplotlib
  - numpy
  - pandas
  - ipykernel
  - plotly
  - pip
  - requests
  - geopandas
  - geopy
  - python-dotenv
  - pip:
    - morethemes
    - cartopy
    - google-analytics-data